require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'
require 'dotenv/load'

# Garante que o ambiente está definido
ENV['RACK_ENV'] ||= 'development'

# Configuração específica para tarefas do banco de dados
namespace :db do
  task :load_config do
    require './app'
  end
end 